apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SECRET_KEY: eW91ci12ZXJ5LXNlY3JldC1rZXk=
  DB_NAME: bGlicmFyeV9kYg==
  DB_USER:ZGphbmdv
  DB_PASSWORD:ZGphbmdvX3Bhc3M=
  MYSQL_ROOT_PASSWORD:cm9vdEAxMjM=
