version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mera_mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    build: .
    container_name: mera_django_app
    command: >
      bash -c "
        echo 'Waiting for MySQL...';
        sleep 10;
        echo 'MySQL is up!';
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn Library_Management.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    restart: always

volumes:
  db_data: {}
